@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Ex2_part2.CustomExecutor",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1519713249 { 
   	label=Ex2_part2
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CustomExecutor1519713249[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CustomExecutor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   Max: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># afterExecute(r: Runnable, t: Throwable)</TD></TR>
<TR><TD ALIGN="LEFT" >+ gracefullyTerminate()</TD></TR>
<TR><TD ALIGN="LEFT" ># newTask(t: Task): TaskFuture&lt;T&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ submit(myFunc: Callable&lt;T&gt;, type: TaskType): Future&lt;T&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ submit(task: Task): Future&lt;T&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ submit(myFunc: Callable&lt;T&gt;): Future&lt;T&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ submitTask(task: Task): Future&lt;T&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Task1519713249[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Task</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   myFunc: Callable [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   priority: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tType: TaskType [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ call(): T</TD></TR>
<TR><TD ALIGN="LEFT" >+ compareTo(t: Task): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ createTask(myFunc: Callable&lt;T&gt;, type: TaskType): Task</TD></TR>
<TR><TD ALIGN="LEFT" >+ createTask(myFunc: Callable&lt;T&gt;): Task</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    

    
}
@enduml